### PR TITLE
feature/support-for-flutter-3-24-3

### PR DESCRIPTION
**Pull request by cristiantorrado-endava**
Changes Summary : 

- [X] Android project structure upgraded to support 8.4 AGP
- [X] Android gradle script and gradle.properties upgraded to support last flutter gradle config style and maitaining compatibility with the previous versions.
- [X] Dart static code watrning and error fixes.
- [X] New Web support implementation by implement video_player_web: ^2.0.10
- [X] Example project upgraded to add web support and upgraded the style for support and build in flutter 3.24.3
- [X] Kotlin bridge fixes.

What it is not included in this update?

- [X] Migration from exo2 player to exo3 we are still compiling without "-Werror" would be nice to have in the future an implementation that use exo3 for android.

### CODE REVIEW

**Comment by bahadirarslan** [comment]
I tried your PR to solve my problem with appinio_video_player.
but I got errors from compiler. 

Am I missing something?

```console

/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:7: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
import static com.google.android.exoplayer2.Player.REPEAT_MODE_ALL;
                                           ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:8: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
import static com.google.android.exoplayer2.Player.REPEAT_MODE_OFF;
                                           ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayerPlugin.java:43: error: cannot find symbol
  private CachedVideoPlayerPlugin(io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                                         ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayerPlugin.java:56: error: cannot find symbol
  public static void registerWith(io.flutter.plugin.common.PluginRegistry.Registrar registrar) {
                                                                         ^
  symbol:   class Registrar
  location: interface PluginRegistry
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:49: warning: [deprecation] ExoPlayer in com.google.android.exoplayer2 has been deprecated
    private final ExoPlayer exoPlayer;
                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:75: warning: [deprecation] ExoPlayer in com.google.android.exoplayer2 has been deprecated
        exoPlayer = new ExoPlayer.Builder(context).build();
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:79: warning: [deprecation] DataSource in com.google.android.exoplayer2.upstream has been deprecated
        DataSource.Factory dataSourceFactory;
        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:92: warning: [deprecation] DefaultDataSource in com.google.android.exoplayer2.upstream has been deprecated
            dataSourceFactory = new DefaultDataSource.Factory(context);
                                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:95: warning: [deprecation] MediaSource in com.google.android.exoplayer2.source has been deprecated
        MediaSource mediaSource = buildMediaSource(uri, dataSourceFactory, formatHint, context);
        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:110: warning: [deprecation] MediaSource in com.google.android.exoplayer2.source has been deprecated
    private MediaSource buildMediaSource(
            ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:111: warning: [deprecation] DataSource in com.google.android.exoplayer2.upstream has been deprecated
            Uri uri, DataSource.Factory mediaDataSourceFactory, String formatHint, Context context) {
                     ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:114: warning: [deprecation] Util in com.google.android.exoplayer2.util has been deprecated
            type = Util.inferContentType(uri.getLastPathSegment());
                   ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:114: warning: [deprecation] inferContentType(String) in Util has been deprecated
            type = Util.inferContentType(uri.getLastPathSegment());
                       ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:117: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
                case FORMAT_SS -> C.TYPE_SS;
                                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:117: warning: [deprecation] TYPE_SS in C has been deprecated
                case FORMAT_SS -> C.TYPE_SS;
                                   ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:118: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
                case FORMAT_DASH -> C.TYPE_DASH;
                                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:118: warning: [deprecation] TYPE_DASH in C has been deprecated
                case FORMAT_DASH -> C.TYPE_DASH;
                                     ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:119: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
                case FORMAT_HLS -> C.TYPE_HLS;
                                   ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:119: warning: [deprecation] TYPE_HLS in C has been deprecated
                case FORMAT_HLS -> C.TYPE_HLS;
                                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:120: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
                case FORMAT_OTHER -> C.TYPE_OTHER;
                                     ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:120: warning: [deprecation] TYPE_OTHER in C has been deprecated
                case FORMAT_OTHER -> C.TYPE_OTHER;
                                      ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:125: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
            case C.TYPE_SS -> new SsMediaSource.Factory(
                 ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:125: warning: [deprecation] TYPE_SS in C has been deprecated
            case C.TYPE_SS -> new SsMediaSource.Factory(
                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:125: warning: [deprecation] SsMediaSource in com.google.android.exoplayer2.source.smoothstreaming has been deprecated
            case C.TYPE_SS -> new SsMediaSource.Factory(
                                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:126: warning: [deprecation] DefaultSsChunkSource in com.google.android.exoplayer2.source.smoothstreaming has been deprecated
                    new DefaultSsChunkSource.Factory(mediaDataSourceFactory),
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:127: warning: [deprecation] DefaultDataSource in com.google.android.exoplayer2.upstream has been deprecated
                    new DefaultDataSource.Factory(context, mediaDataSourceFactory))
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:128: warning: [deprecation] MediaItem in com.google.android.exoplayer2 has been deprecated
                    .createMediaSource(MediaItem.fromUri(uri));
                                       ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:129: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
            case C.TYPE_DASH -> new DashMediaSource.Factory(
                 ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:129: warning: [deprecation] TYPE_DASH in C has been deprecated
            case C.TYPE_DASH -> new DashMediaSource.Factory(
                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:129: warning: [deprecation] DashMediaSource in com.google.android.exoplayer2.source.dash has been deprecated
            case C.TYPE_DASH -> new DashMediaSource.Factory(
                                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:130: warning: [deprecation] DefaultDashChunkSource in com.google.android.exoplayer2.source.dash has been deprecated
                    new DefaultDashChunkSource.Factory(mediaDataSourceFactory),
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:131: warning: [deprecation] DefaultDataSource in com.google.android.exoplayer2.upstream has been deprecated
                    new DefaultDataSource.Factory(context, mediaDataSourceFactory))
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:132: warning: [deprecation] MediaItem in com.google.android.exoplayer2 has been deprecated
                    .createMediaSource(MediaItem.fromUri(uri));
                                       ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:133: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
            case C.TYPE_HLS ->
                 ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:133: warning: [deprecation] TYPE_HLS in C has been deprecated
            case C.TYPE_HLS ->
                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:134: warning: [deprecation] HlsMediaSource in com.google.android.exoplayer2.source.hls has been deprecated
                    new HlsMediaSource.Factory(mediaDataSourceFactory)
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:135: warning: [deprecation] MediaItem in com.google.android.exoplayer2 has been deprecated
                            .createMediaSource(MediaItem.fromUri(uri));
                                               ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:136: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
            case C.TYPE_OTHER ->
                 ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:136: warning: [deprecation] TYPE_OTHER in C has been deprecated
            case C.TYPE_OTHER ->
                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:137: warning: [deprecation] ProgressiveMediaSource in com.google.android.exoplayer2.source has been deprecated
                    new ProgressiveMediaSource.Factory(mediaDataSourceFactory)
                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:138: warning: [deprecation] MediaItem in com.google.android.exoplayer2 has been deprecated
                            .createMediaSource(MediaItem.fromUri(uri));
                                               ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:165: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
                new Player.Listener() {
                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:179: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
                        if (playbackState == Player.STATE_BUFFERING) {
                                             ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:182: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
                        } else if (playbackState == Player.STATE_READY) {
                                                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:187: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
                        } else if (playbackState == Player.STATE_ENDED) {
                                                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:193: warning: [deprecation] Player in com.google.android.exoplayer2 has been deprecated
                        if (playbackState != Player.STATE_BUFFERING) {
                                             ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:199: warning: [deprecation] PlaybackException in com.google.android.exoplayer2 has been deprecated
                    public void onPlayerError(@NonNull PlaybackException error) {
                                                       ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:215: warning: [deprecation] ExoPlayer in com.google.android.exoplayer2 has been deprecated
    private static void setAudioAttributes(ExoPlayer exoPlayer, boolean isMixMode) {
                                           ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:217: warning: [deprecation] C in com.google.android.exoplayer2 has been deprecated
                new AudioAttributes.Builder().setContentType(com.google.android.exoplayer2.C.AUDIO_CONTENT_TYPE_MOVIE).build(), !isMixMode);
                                                                                          ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:217: warning: [deprecation] AudioAttributes in com.google.android.exoplayer2.audio has been deprecated
                new AudioAttributes.Builder().setContentType(com.google.android.exoplayer2.C.AUDIO_CONTENT_TYPE_MOVIE).build(), !isMixMode);
                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CachedVideoPlayer.java:259: warning: [deprecation] Format in com.google.android.exoplayer2 has been deprecated
                Format videoFormat = exoPlayer.getVideoFormat();
                ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:18: warning: [deprecation] DataSource in com.google.android.exoplayer2.upstream has been deprecated
class CacheDataSourceFactory implements DataSource.Factory {
                                        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:22: warning: [deprecation] DefaultHttpDataSource in com.google.android.exoplayer2.upstream has been deprecated
    private final DefaultHttpDataSource.Factory defaultHttpDataSourceFactory;
                  ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:30: warning: [deprecation] DefaultHttpDataSource in com.google.android.exoplayer2.upstream has been deprecated
        defaultHttpDataSourceFactory = new DefaultHttpDataSource.Factory();
                                           ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:41: warning: [deprecation] DataSource in com.google.android.exoplayer2.upstream has been deprecated
    public DataSource createDataSource() {
           ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:42: warning: [deprecation] DefaultBandwidthMeter in com.google.android.exoplayer2.upstream has been deprecated
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter.Builder(context).build();
        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:42: warning: [deprecation] DefaultBandwidthMeter in com.google.android.exoplayer2.upstream has been deprecated
        DefaultBandwidthMeter bandwidthMeter = new DefaultBandwidthMeter.Builder(context).build();
                                                   ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:44: warning: [deprecation] DefaultDataSource in com.google.android.exoplayer2.upstream has been deprecated
        DefaultDataSource.Factory defaultDatasourceFactory = new DefaultDataSource.Factory(this.context, defaultHttpDataSourceFactory);
        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:44: warning: [deprecation] DefaultDataSource in com.google.android.exoplayer2.upstream has been deprecated
        DefaultDataSource.Factory defaultDatasourceFactory = new DefaultDataSource.Factory(this.context, defaultHttpDataSourceFactory);
                                                                 ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:47: warning: [deprecation] SimpleCache in com.google.android.exoplayer2.upstream.cache has been deprecated
        SimpleCache simpleCache = SimpleCacheSingleton.getInstance(context, maxCacheSize).simpleCache;
        ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:48: warning: [deprecation] CacheDataSource in com.google.android.exoplayer2.upstream.cache has been deprecated
        return new CacheDataSource(simpleCache, defaultDatasourceFactory.createDataSource(),
                   ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:49: warning: [deprecation] FileDataSource in com.google.android.exoplayer2.upstream has been deprecated
                new FileDataSource(), new CacheDataSink(simpleCache, maxFileSize),
                    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:49: warning: [deprecation] CacheDataSink in com.google.android.exoplayer2.upstream.cache has been deprecated
                new FileDataSource(), new CacheDataSink(simpleCache, maxFileSize),
                                          ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:50: warning: [deprecation] CacheDataSource in com.google.android.exoplayer2.upstream.cache has been deprecated
                CacheDataSource.FLAG_BLOCK_ON_CACHE | CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR, null);
                ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/CacheDataSourceFactory.java:50: warning: [deprecation] CacheDataSource in com.google.android.exoplayer2.upstream.cache has been deprecated
                CacheDataSource.FLAG_BLOCK_ON_CACHE | CacheDataSource.FLAG_IGNORE_CACHE_ON_ERROR, null);
                                                      ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/SimpleCacheSingleton.java:12: warning: [deprecation] LeastRecentlyUsedCacheEvictor in com.google.android.exoplayer2.upstream.cache has been deprecated
    LeastRecentlyUsedCacheEvictor evictor;
    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/SimpleCacheSingleton.java:13: warning: [deprecation] SimpleCache in com.google.android.exoplayer2.upstream.cache has been deprecated
    SimpleCache simpleCache;
    ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/SimpleCacheSingleton.java:18: warning: [deprecation] LeastRecentlyUsedCacheEvictor in com.google.android.exoplayer2.upstream.cache has been deprecated
        evictor = new LeastRecentlyUsedCacheEvictor(maxCacheSize);
                      ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/SimpleCacheSingleton.java:19: warning: [deprecation] SimpleCache in com.google.android.exoplayer2.upstream.cache has been deprecated
        simpleCache = new SimpleCache(new File(context.getCacheDir(), "media"), evictor, new StandaloneDatabaseProvider(context));
                          ^
/Users/bahadirarslan/.pub-cache/git/flutter_cached_video_player-9051875026cf9ceac1265ca50d119ddb43076251/android/src/main/java/com/lazyarts/vikram/cached_video_player/SimpleCacheSingleton.java:19: warning: [deprecation] StandaloneDatabaseProvider in com.google.android.exoplayer2.database has been deprecated
        simpleCache = new SimpleCache(new File(context.getCacheDir(), "media"), evictor, new StandaloneDatabaseProvider(context));
                                                                                          ^
2 errors
68 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cached_video_player:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.

BUILD FAILED in 42s

┌─ Flutter Fix ───────────────────────────────────────────────────────────────────────────────────┐
│ [!] Consult the error logs above to identify any broken plugins, specifically those containing  │
│ "error: cannot find symbol..."                                                                  │
│ This issue is likely caused by v1 embedding removal and the plugin's continued usage of removed │
│ references to the v1 embedding.                                                                 │
│ To fix this error, please upgrade your current package's dependencies to latest versions by     │
│ running `flutter pub upgrade`.                                                                  │
│ If that does not work, please file an issue for the problematic plugin(s) here:                 │
│ https://github.com/flutter/flutter/issues                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────┘
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
```

**Comment by cristiantorrado-endava** [comment]
@bahadirarslan  Yes those errors are because the original plugin use exo 2 as video  player api in android. Exo2 had been dprecated. In my PR details commented that this doesn't inlcude exo2 to exo3 migration.  Later i will help with exo 3 migration but at the moment you can use the exo2 player by compiling the library without  "-Werror" flag : 


`def args = ["-Xlint:deprecation","-Xlint:unchecked","-Werror"] -> def args = ["-Xlint:deprecation", "-Xlint:unchecked"]
`
This is the workarround. Appart of nexo3 migration another change its needed in base to my research: This plugin use the video_player_platform_interface and the new version of the interface has breacking changes also.

But at the moment with this branch i could unblock the build in flutter 3 with agp 8.4 at the moment i could use in my customer app without issue and the plan is to try to collaborate with another community members in update this plugin.

**Comment by bahadirarslan** [comment]
Thanks for your effort and help but I am trying to replace this package with another one. Because the owner doesn't care and probably we will face another issues in the future if can solve this today.
Normally I am using appinio package which depends on this package. Both packages look like abandoned. So the best way for me is finding another solution.

**Comment by cristiantorrado-endava** [comment]
@bahadirarslan Totally in my case this is the short-time action but alse we are evaluating to replace with another one .This library came from the legacy version of the app. I hope the best for your project. And please share if you find a better library to implement.

**Comment by bahadirarslan** [comment]
> @bahadirarslan Totally in my case this is the short-time action but alse we are evaluating to replace with another one .This library came from the legacy version of the app. I hope the best for your project. And please share if you find a better library to implement.

I switched to [chewie](https://pub.dev/packages/chewie) player. It worked without a problem.
